image: Visual Studio 2022
skip_commits:
  message: /docs|Merge pull request.*/
build_script:
- ps: >-
    dotnet build FodySample --configuration Release

    dotnet test FodySample --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\*.nupkg